# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [54]:
# Question 1
print(df.shape)
print(df.columns)

# Question 2
print(df.info())

# Question 3
print(df.head(10))

(891, 15)
Index(['USDtoEURO', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'UStoEURO',
       'SubAgeAVG'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   USDtoEURO    891 non-null    float64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    object
 5   Sex          891 non-null    object
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    object
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    object
 12  Embarked     889 non-null    object
 13  UStoEURO     891 non-null    float64
 14  SubAgeAVG    714 non-null    float64
dtypes: float64(5), int64(5), object(5)
memory usage: 104.5+ KB
None
   USDtoEURO  PassengerId  Survived  Pclass  \
0   6.235000            1         0       3
1  61.303638            2         1       1
2   6.815500            3         1       3
3  45.666000            4         1       1
4   6.923000            5         0       3
5   7.274138            6         0       3
6  44.601750            7         0       1
7  18.124500            8         0       3
8   9.574638            9         1       3
9  25.860888           10         1       2

                                                Name     Sex        Age  \
0                            Braund, Mr. Owen Harris    male  -7.699118
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   8.300882
2                              Heikkinen, Miss Laina  female  -3.699118
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   5.300882
4                           Allen, Mr. William Henry    male   5.300882
5                                   Moran, Mr. James    male        NaN
6                            McCarthy, Mr. Timothy J    male  24.300882
7                      Palsson, Master Gosta Leonard    male -27.699118
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  -2.699118
9                Nasser, Mrs. Nicholas (Adele Achem)  female -15.699118

   SibSp  Parch            Ticket     Fare Cabin Embarked   UStoEURO  \
0      1      0         A/5 21171   7.2500   NaN        S   6.235000
1      1      0          PC 17599  71.2833   C85        C  61.303638
2      0      0  STON/O2. 3101282   7.9250   NaN        S   6.815500
3      1      0            113803  53.1000  C123        S  45.666000
4      0      0            373450   8.0500   NaN        S   6.923000
5      0      0            330877   8.4583   NaN        Q   7.274138
6      0      0             17463  51.8625   E46        S  44.601750
7      3      1            349909  21.0750   NaN        S  18.124500
8      0      2            347742  11.1333   NaN        S   9.574638
9      1      0            237736  30.0708   NaN        C  25.860888

   SubAgeAVG
0  -7.699118
1   8.300882
2  -3.699118
3   5.300882
4   5.300882
5        NaN
6  24.300882
7 -27.699118
8  -2.699118
9 -15.699118

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [22]:
# Question 1
df[[Name]]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [23]:
# Question 2
df[['Age', 'Fare', 'Parch']]

      Age     Fare  Parch
0    22.0   7.2500      0
1    38.0  71.2833      0
2    26.0   7.9250      0
3    35.0  53.1000      0
4    35.0   8.0500      0
..    ...      ...    ...
886  27.0  13.0000      0
887  19.0  30.0000      0
888   NaN  23.4500      2
889  26.0  30.0000      0
890  32.0   7.7500      0

[891 rows x 3 columns]

In [27]:
# Question 3
df.iloc[4]

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object

In [31]:
# Question 4
df.iloc[5:20, 0:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750
14,15,0,3,"Vestrom, Miss Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000
16,17,0,3,"Rice, Master Eugene",male,2.0,4,1,382652,29.1250
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [ ]:
# Question 1
df.loc[df['Age'] > 60]

In [ ]:
# Question 2
df.loc[(df['Fare'] > 100) & (df['Pclass'] == 1)]

In [37]:
# Question 3
df.loc[df['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [33]:
# Question 1
df.reindex(index=df.index[::-1])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [36]:
# Question 2
df.drop(columns=['Parch'])

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,NaN,Q

In [38]:
# Question 3
df.dropna(subset=['Age'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [49]:
# Question 1
df['UStoEURO'] = df['Fare']*0.86
df.head(10)

,USDtoEURO,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO
0,6.235000,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,61.303638,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,6.815500,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,45.666000,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,6.923000,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
5,7.274138,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138
6,44.601750,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750
7,18.124500,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500
8,9.574638,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638
9,25.860888,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888

In [56]:
# Question 2
df['SubAgeAVG'] = df['Age'] - df['Age'].mean()
df.head(10)

,USDtoEURO,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG
0,6.235000,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118
1,61.303638,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882
2,6.815500,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118
3,45.666000,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S,45.666000,5.300882
4,6.923000,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S,6.923000,5.300882
5,7.274138,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN
6,44.601750,7,0,1,"McCarthy, Mr. Timothy J",male,24.300882,0,0,17463,51.8625,E46,S,44.601750,24.300882
7,18.124500,8,0,3,"Palsson, Master Gosta Leonard",male,-27.699118,3,1,349909,21.0750,NaN,S,18.124500,-27.699118
8,9.574638,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,-2.699118,0,2,347742,11.1333,NaN,S,9.574638,-2.699118
9,25.860888,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,-15.699118,1,0,237736,30.0708,NaN,C,25.860888,-15.699118

In [57]:
# Question 3
df[['Fare','Age']].subtract([10,5])

        Fare        Age
0    -2.7500 -12.699118
1    61.2833   3.300882
2    -2.0750  -8.699118
3    43.1000   0.300882
4    -1.9500   0.300882
..       ...        ...
886   3.0000  -7.699118
887  20.0000 -15.699118
888  13.4500        NaN
889  20.0000  -8.699118
890  -2.2500  -2.699118

[891 rows x 2 columns]

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [59]:
# Question 1
df['CharNums'] = df['Name'].apply(len)
df.head(10)

,USDtoEURO,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums
0,6.235000,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23
1,61.303638,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51
2,6.815500,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21
3,45.666000,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S,45.666000,5.300882,44
4,6.923000,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24
5,7.274138,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16
6,44.601750,7,0,1,"McCarthy, Mr. Timothy J",male,24.300882,0,0,17463,51.8625,E46,S,44.601750,24.300882,23
7,18.124500,8,0,3,"Palsson, Master Gosta Leonard",male,-27.699118,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29
8,9.574638,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,-2.699118,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49
9,25.860888,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,-15.699118,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35

In [60]:
# Question 2
df['FareAgeDiff'] = df['Fare'] - df['Age']
df.head(10)

,USDtoEURO,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums,FareAgeDiff
0,6.235000,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23,14.949118
1,61.303638,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51,62.982418
2,6.815500,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21,11.624118
3,45.666000,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S,45.666000,5.300882,44,47.799118
4,6.923000,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24,2.749118
5,7.274138,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16,NaN
6,44.601750,7,0,1,"McCarthy, Mr. Timothy J",male,24.300882,0,0,17463,51.8625,E46,S,44.601750,24.300882,23,27.561618
7,18.124500,8,0,3,"Palsson, Master Gosta Leonard",male,-27.699118,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29,48.774118
8,9.574638,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,-2.699118,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49,13.832418
9,25.860888,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,-15.699118,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35,45.769918

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).