# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [22]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [23]:
# Question 1
print(df.shape)
print(df.columns)

# Question 2
print(df.info())

# Question 3
print(df.head(10))

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [24]:
# Question 1
df[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [25]:
# Question 2
df[['Age', 'Fare', 'Parch']]

      Age     Fare  Parch
0    22.0   7.2500      0
1    38.0  71.2833      0
2    26.0   7.9250      0
3    35.0  53.1000      0
4    35.0   8.0500      0
..    ...      ...    ...
886  27.0  13.0000      0
887  19.0  30.0000      0
888   NaN  23.4500      2
889  26.0  30.0000      0
890  32.0   7.7500      0

[891 rows x 3 columns]

In [26]:
# Question 3
df.iloc[4]

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object

In [27]:
# Question 4
df.iloc[5:20, 0:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750
14,15,0,3,"Vestrom, Miss Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000
16,17,0,3,"Rice, Master Eugene",male,2.0,4,1,382652,29.1250
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [28]:
# Question 1
df.loc[df['Age'] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [29]:
# Question 2
df.loc[(df['Fare'] > 100) & (df['Pclass'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [30]:
# Question 3
df.loc[df['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [31]:
# Question 1
df.reindex(index=df.index[::-1])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [32]:
# Question 2
df.drop(columns=['Parch'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN,Q

In [33]:
# Question 3
df.dropna(subset=['Age'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [34]:
# Question 1
df['UStoEURO'] = df['Fare']*0.86
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888

In [35]:
# Question 2
df['SubAgeAVG'] = df['Age'] - df['Age'].mean()
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750,24.300882
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500,-27.699118
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638,-2.699118
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888,-15.699118

In [36]:
# Question 3
df[['Fare','Age']].subtract([10,5])

        Fare   Age
0    -2.7500  17.0
1    61.2833  33.0
2    -2.0750  21.0
3    43.1000  30.0
4    -1.9500  30.0
..       ...   ...
886   3.0000  22.0
887  20.0000  14.0
888  13.4500   NaN
889  20.0000  21.0
890  -2.2500  27.0

[891 rows x 2 columns]

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [37]:
# Question 1
df['CharNums'] = df['Name'].apply(len)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750,24.300882,23
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35

In [38]:
# Question 2
df['FareAgeDiff'] = df['Fare'] - df['Age']
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums,FareAgeDiff
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51,33.2833
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882,44,18.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24,-26.9500
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750,24.300882,23,-2.1375
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29,19.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49,-15.8667
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35,16.0708

In [39]:
df.round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums,FareAgeDiff
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.2,-7.7,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,61.3,8.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,6.8,-3.7,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,45.7,5.3,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,6.9,5.3,24,-27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S,11.2,-2.7,21,-14.0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,25.8,-10.7,27,11.0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4,NaN,S,20.2,NaN,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,25.8,-3.7,21,4.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.8,NaN,Q,6.7,2.3,19,-24.2

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [40]:
# Question 1
df['NumGender'] = df['Sex'].map({'male': 0,'female': 1})
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums,FareAgeDiff,NumGender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23,-14.7500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51,33.2833,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21,-18.0750,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882,44,18.1000,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24,-26.9500,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16,NaN,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750,24.300882,23,-2.1375,0
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29,19.0750,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49,-15.8667,1
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35,16.0708,1

In [45]:
# Question 2

df['AgeCategory'] = 'aduilt'
df.loc[df['Age'] < 18, 'AgeCategory'] = 'child'
df.loc[df['Age'] >= 60, 'AgeCategory'] = 'senior'
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,UStoEURO,SubAgeAVG,CharNums,FareAgeDiff,NumGender,AgeCategory
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23,-14.7500,0,aduilt
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51,33.2833,1,aduilt
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21,-18.0750,1,aduilt
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882,44,18.1000,1,aduilt
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24,-26.9500,0,aduilt
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.274138,NaN,16,NaN,0,aduilt
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,44.601750,24.300882,23,-2.1375,0,aduilt
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,18.124500,-27.699118,29,19.0750,0,child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,9.574638,-2.699118,49,-15.8667,1,aduilt
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,25.860888,-15.699118,35,16.0708,1,child

### Part 8: Solve chosen task without using Pandas ###
1. Select a single row from the dataset.

2. Show only the rows where the age is above 60.

3. Remove one column from the dataset.

In [47]:
# converting dataset into a list
data = df.values.tolist()
print(data)

[[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0, 'A/5 21171', 7.25, nan, 'S', 6.235, -7.69911764705882, 23, -14.75, 0, 'aduilt'], [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 61.303638, 8.30088235294118, 51, 33.2833, 1, 'aduilt'], [3, 1, 3, 'Heikkinen, Miss Laina', 'female', 26.0, 0, 0, 'STON/O2. 3101282', 7.925, nan, 'S', 6.8155, -3.69911764705882, 21, -18.075, 1, 'aduilt'], [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S', 45.666000000000004, 5.30088235294118, 44, 18.1, 1, 'aduilt'], [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0, '373450', 8.05, nan, 'S', 6.923000000000001, 5.30088235294118, 24, -26.95, 0, 'aduilt'], [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583, nan, 'Q', 7.274138, nan, 16, nan, 0, 'aduilt'], [7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0, '17463', 51.8625, 'E46', 'S', 44.601749999999996, 24.30088235294118, 23, -2.137500000000003, 0, 'aduilt'], [8, 0, 3, 'Palsson, Master Gosta Leonard', 'male', 2.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998, -27.69911764705882, 29, 19.075, 0, 'child'], [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female', 27.0, 0, 2, '347742', 11.1333, nan, 'S', 9.574638, -2.69911764705882, 49, -15.8667, 1, 'aduilt'], [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0, 1, 0, '237736', 30.0708, nan, 'C', 25.860888, -15.69911764705882, 35, 16.0708, 1, 'child'], [11, 1, 3, 'Sandstrom, Miss Marguerite Rut', 'female', 4.0, 1, 1, 'PP 9549', 16.7, 'G6', 'S', 14.361999999999998, -25.69911764705882, 30, 12.7, 1, 'child'], [12, 1, 1, 'Bonnell, Miss Elizabeth', 'female', 58.0, 0, 0, '113783', 26.55, 'C103', 'S', 22.833000000000002, 28.30088235294118, 23, -31.45, 1, 'aduilt'], [13, 0, 3, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0, 'A/5. 2151', 8.05, nan, 'S', 6.923000000000001, -9.69911764705882, 30, -11.95, 0, 'aduilt'], [14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5, '347082', 31.275, nan, 'S', 26.8965, 9.30088235294118, 27, -7.725000000000001, 0, 'aduilt'], [15, 0, 3, 'Vestrom, Miss Hulda Amanda Adolfina', 'female', 14.0, 0, 0, '350406', 7.8542, nan, 'S', 6.754612, -15.69911764705882, 35, -6.1458, 1, 'child'], [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0, 0, '248706', 16.0, nan, 'S', 13.76, 25.30088235294118, 32, -39.0, 1, 'aduilt'], [17, 0, 3, 'Rice, Master Eugene', 'male', 2.0, 4, 1, '382652', 29.125, nan, 'Q', 25.0475, -27.69911764705882, 19, 27.125, 0, 'child'], [18, 1, 2, 'Williams, Mr. Charles Eugene', 'male', nan, 0, 0, '244373', 13.0, nan, 'S', 11.18, nan, 28, nan, 0, 'aduilt'], [19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female', 31.0, 1, 0, '345763', 18.0, nan, 'S', 15.48, 1.30088235294118, 55, -13.0, 1, 'aduilt'], [20, 1, 3, 'Masselmani, Mrs. Fatima', 'female', nan, 0, 0, '2649', 7.225, nan, 'C', 6.2135, nan, 23, nan, 1, 'aduilt'], [21, 0, 2, 'Fynney, Mr. Joseph J', 'male', 35.0, 0, 0, '239865', 26.0, nan, 'S', 22.36, 5.30088235294118, 20, -9.0, 0, 'aduilt'], [22, 1, 2, 'Beesley, Mr. Lawrence', 'male', 34.0, 0, 0, '248698', 13.0, 'D56', 'S', 11.18, 4.30088235294118, 21, -21.0, 0, 'aduilt'], [23, 1, 3, 'McGowan, Miss Anna "Annie"', 'female', 15.0, 0, 0, '330923', 8.0292, nan, 'Q', 6.905111999999999, -14.69911764705882, 26, -6.9708000000000006, 1, 'child'], [24, 1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 0, 0, '113788', 35.5, 'A6', 'S', 30.53, -1.69911764705882, 28, 7.5, 0, 'aduilt'], [25, 0, 3, 'Palsson, Miss Torborg Danira', 'female', 8.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998, -21.69911764705882, 28, 13.075, 1, 'child'], [26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female', 38.0, 1, 5, '347077', 31.3875, nan, 'S', 26.99325, 8.30088235294118, 57, -6.612500000000001, 1, 'aduilt'], [27, 0, 3, 'Emir, Mr. Farred Chehab', 'male', nan, 0, 0, '2631', 7.225, nan, 'C', 6.2135, nan, 23, nan, 0, 'aduilt'], [28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, -10.69911764705882, 30, 244.0, 0, 'aduilt'], [29, 1, 3, 'O\'Dwyer, Miss Ellen "Nellie"', 'female', nan, 0, 0, '330959', 7.8792, nan, 'Q', 6.7761119999999995, nan, 28, nan, 1, 'aduilt'], [30, 0, 3, 'Todoroff, Mr. Lalio', 'male', nan, 0, 0, '349216', 7.8958, nan, 'S', 6.790388, nan, 19, nan, 0, 'aduilt'], [31, 0, 1, 'Uruchurtu, Don. Manuel E', 'male', 40.0, 0, 0, 'PC 17601', 27.7208, nan, 'C', 23.839888, 10.30088235294118, 24, -12.2792, 0, 'aduilt'], [32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'female', nan, 1, 0, 'PC 17569', 146.5208, 'B78', 'C', 126.00788800000001, nan, 46, nan, 1, 'aduilt'], [33, 1, 3, 'Glynn, Miss Mary Agatha', 'female', nan, 0, 0, '335677', 7.75, nan, 'Q', 6.665, nan, 23, nan, 1, 'aduilt'], [34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0, 'C.A. 24579', 10.5, nan, 'S', 9.03, 36.30088235294118, 21, -55.5, 0, 'senior'], [35, 0, 1, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 1, 0, 'PC 17604', 82.1708, nan, 'C', 70.666888, -1.69911764705882, 23, 54.1708, 0, 'aduilt'], [36, 0, 1, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 1, 0, '113789', 52.0, nan, 'S', 44.72, 12.30088235294118, 30, 10.0, 0, 'aduilt'], [37, 1, 3, 'Mamee, Mr. Hanna', 'male', nan, 0, 0, '2677', 7.2292, nan, 'C', 6.217111999999999, nan, 16, nan, 0, 'aduilt'], [38, 0, 3, 'Cann, Mr. Ernest Charles', 'male', 21.0, 0, 0, 'A./5. 2152', 8.05, nan, 'S', 6.923000000000001, -8.69911764705882, 24, -12.95, 0, 'aduilt'], [39, 0, 3, 'Vander Planke, Miss Augusta Maria', 'female', 18.0, 2, 0, '345764', 18.0, nan, 'S', 15.48, -11.69911764705882, 33, 0.0, 1, 'aduilt'], [40, 1, 3, 'Nicola-Yarred, Miss Jamila', 'female', 14.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862, -15.69911764705882, 26, -2.7583, 1, 'child'], [41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female', 40.0, 1, 0, '7546', 9.475, nan, 'S', 8.1485, 10.30088235294118, 46, -30.525, 1, 'aduilt'], [42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female', 27.0, 1, 0, '11668', 21.0, nan, 'S', 18.06, -2.69911764705882, 56, -6.0, 1, 'aduilt'], [43, 0, 3, 'Kraeff, Mr. Theodor', 'male', nan, 0, 0, '349253', 7.8958, nan, 'C', 6.790388, nan, 19, nan, 0, 'aduilt'], [44, 1, 2, 'Laroche, Miss Simonne Marie Anne Andree', 'female', 3.0, 1, 2, 'SC/Paris 2123', 41.5792, nan, 'C', 35.758112, -26.69911764705882, 39, 38.5792, 1, 'child'], [45, 1, 3, 'Devaney, Miss Margaret Delia', 'female', 19.0, 0, 0, '330958', 7.8792, nan, 'Q', 6.7761119999999995, -10.69911764705882, 28, -11.1208, 1, 'aduilt'], [46, 0, 3, 'Rogers, Mr. William John', 'male', nan, 0, 0, 'S.C./A.4. 23567', 8.05, nan, 'S', 6.923000000000001, nan, 24, nan, 0, 'aduilt'], [47, 0, 3, 'Lennon, Mr. Denis', 'male', nan, 1, 0, '370371', 15.5, nan, 'Q', 13.33, nan, 17, nan, 0, 'aduilt'], [48, 1, 3, "O'Driscoll, Miss Bridget", 'female', nan, 0, 0, '14311', 7.75, nan, 'Q', 6.665, nan, 24, nan, 1, 'aduilt'], [49, 0, 3, 'Samaan, Mr. Youssef', 'male', nan, 2, 0, '2662', 21.6792, nan, 'C', 18.644112, nan, 19, nan, 0, 'aduilt'], [50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female', 18.0, 1, 0, '349237', 17.8, nan, 'S', 15.308, -11.69911764705882, 45, -0.1999999999999993, 1, 'aduilt'], [51, 0, 3, 'Panula, Master Juha Niilo', 'male', 7.0, 4, 1, '3101295', 39.6875, nan, 'S', 34.13125, -22.69911764705882, 25, 32.6875, 0, 'child'], [52, 0, 3, 'Nosworthy, Mr. Richard Cater', 'male', 21.0, 0, 0, 'A/4. 39886', 7.8, nan, 'S', 6.708, -8.69911764705882, 28, -13.2, 0, 'aduilt'], [53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 1, 0, 'PC 17572', 76.7292, 'D33', 'C', 65.98711200000001, 19.30088235294118, 40, 27.729200000000006, 1, 'aduilt'], [54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female', 29.0, 1, 0, '2926', 26.0, nan, 'S', 22.36, -0.6991176470588201, 50, -3.0, 1, 'aduilt'], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1, '113509', 61.9792, 'B30', 'C', 53.302112, 35.30088235294118, 30, -3.0208000000000013, 0, 'senior'], [56, 1, 1, 'Woolner, Mr. Hugh', 'male', nan, 0, 0, '19947', 35.5, 'C52', 'S', 30.53, nan, 17, nan, 0, 'aduilt'], [57, 1, 2, 'Rugg, Miss Emily', 'female', 21.0, 0, 0, 'C.A. 31026', 10.5, nan, 'S', 9.03, -8.69911764705882, 16, -10.5, 1, 'aduilt'], [58, 0, 3, 'Novel, Mr. Mansouer', 'male', 28.5, 0, 0, '2697', 7.2292, nan, 'C', 6.217111999999999, -1.19911764705882, 19, -21.2708, 0, 'aduilt'], [59, 1, 2, 'West, Miss Constance Mirium', 'female', 5.0, 1, 2, 'C.A. 34651', 27.75, nan, 'S', 23.865, -24.69911764705882, 27, 22.75, 1, 'child'], [60, 0, 3, 'Goodwin, Master William Frederick', 'male', 11.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996, -18.69911764705882, 33, 35.9, 0, 'child'], [61, 0, 3, 'Sirayanian, Mr. Orsen', 'male', 22.0, 0, 0, '2669', 7.2292, nan, 'C', 6.217111999999999, -7.69911764705882, 21, -14.770800000000001, 0, 'aduilt'], [62, 1, 1, 'Icard, Miss Amelie', 'female', 38.0, 0, 0, '113572', 80.0, 'B28', nan, 68.8, 8.30088235294118, 18, 42.0, 1, 'aduilt'], [63, 0, 1, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 1, 0, '36973', 83.475, 'C83', 'S', 71.7885, 15.30088235294118, 27, 38.474999999999994, 0, 'aduilt'], [64, 0, 3, 'Skoog, Master Harald', 'male', 4.0, 3, 2, '347088', 27.9, nan, 'S', 23.994, -25.69911764705882, 20, 23.9, 0, 'child'], [65, 0, 1, 'Stewart, Mr. Albert A', 'male', nan, 0, 0, 'PC 17605', 27.7208, nan, 'C', 23.839888, nan, 21, nan, 0, 'aduilt'], [66, 1, 3, 'Moubarek, Master Gerios', 'male', nan, 1, 1, '2661', 15.2458, nan, 'C', 13.111388, nan, 23, nan, 0, 'aduilt'], [67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 'female', 29.0, 0, 0, 'C.A. 29395', 10.5, 'F33', 'S', 9.03, -0.6991176470588201, 28, -18.5, 1, 'aduilt'], [68, 0, 3, 'Crease, Mr. Ernest James', 'male', 19.0, 0, 0, 'S.P. 3464', 8.1583, nan, 'S', 7.016138000000001, -10.69911764705882, 24, -10.8417, 0, 'aduilt'], [69, 1, 3, 'Andersson, Miss Erna Alexandra', 'female', 17.0, 4, 2, '3101281', 7.925, nan, 'S', 6.8155, -12.69911764705882, 30, -9.075, 1, 'child'], [70, 0, 3, 'Kink, Mr. Vincenz', 'male', 26.0, 2, 0, '315151', 8.6625, nan, 'S', 7.44975, -3.69911764705882, 17, -17.3375, 0, 'aduilt'], [71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 'male', 32.0, 0, 0, 'C.A. 33111', 10.5, nan, 'S', 9.03, 2.30088235294118, 26, -21.5, 0, 'aduilt'], [72, 0, 3, 'Goodwin, Miss Lillian Amy', 'female', 16.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996, -13.69911764705882, 25, 30.9, 1, 'child'], [73, 0, 2, 'Hood, Mr. Ambrose Jr', 'male', 21.0, 0, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21, -8.69911764705882, 20, 52.5, 0, 'aduilt'], [74, 0, 3, 'Chronopoulos, Mr. Apostolos', 'male', 26.0, 1, 0, '2680', 14.4542, nan, 'C', 12.430612, -3.69911764705882, 27, -11.5458, 0, 'aduilt'], [75, 1, 3, 'Bing, Mr. Lee', 'male', 32.0, 0, 0, '1601', 56.4958, nan, 'S', 48.586388, 2.30088235294118, 13, 24.495800000000003, 0, 'aduilt'], [76, 0, 3, 'Moen, Mr. Sigurd Hansen', 'male', 25.0, 0, 0, '348123', 7.65, 'F G73', 'S', 6.579000000000001, -4.69911764705882, 23, -17.35, 0, 'aduilt'], [77, 0, 3, 'Staneff, Mr. Ivan', 'male', nan, 0, 0, '349208', 7.8958, nan, 'S', 6.790388, nan, 17, nan, 0, 'aduilt'], [78, 0, 3, 'Moutal, Mr. Rahamin Haim', 'male', nan, 0, 0, '374746', 8.05, nan, 'S', 6.923000000000001, nan, 24, nan, 0, 'aduilt'], [79, 1, 2, 'Caldwell, Master Alden Gates', 'male', 0.83, 0, 2, '248738', 29.0, nan, 'S', 24.94, -28.86911764705882, 28, 28.17, 0, 'child'], [80, 1, 3, 'Dowdell, Miss Elizabeth', 'female', 30.0, 0, 0, '364516', 12.475, nan, 'S', 10.7285, 0.30088235294117993, 23, -17.525, 1, 'aduilt'], [81, 0, 3, 'Waelens, Mr. Achille', 'male', 22.0, 0, 0, '345767', 9.0, nan, 'S', 7.74, -7.69911764705882, 20, -13.0, 0, 'aduilt'], [82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 'male', 29.0, 0, 0, '345779', 9.5, nan, 'S', 8.17, -0.6991176470588201, 27, -19.5, 0, 'aduilt'], [83, 1, 3, 'McDermott, Miss Brigdet Delia', 'female', nan, 0, 0, '330932', 7.7875, nan, 'Q', 6.6972499999999995, nan, 29, nan, 1, 'aduilt'], [84, 0, 1, 'Carrau, Mr. Francisco M', 'male', 28.0, 0, 0, '113059', 47.1, nan, 'S', 40.506, -1.69911764705882, 23, 19.1, 0, 'aduilt'], [85, 1, 2, 'Ilett, Miss Bertha', 'female', 17.0, 0, 0, 'SO/C 14885', 10.5, nan, 'S', 9.03, -12.69911764705882, 18, -6.5, 1, 'child'], [86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female', 33.0, 3, 0, '3101278', 15.85, nan, 'S', 13.631, 3.30088235294118, 55, -17.15, 1, 'aduilt'], [87, 0, 3, 'Ford, Mr. William Neal', 'male', 16.0, 1, 3, 'W./C. 6608', 34.375, nan, 'S', 29.5625, -13.69911764705882, 22, 18.375, 0, 'child'], [88, 0, 3, 'Slocovski, Mr. Selman Francis', 'male', nan, 0, 0, 'SOTON/OQ 392086', 8.05, nan, 'S', 6.923000000000001, nan, 29, nan, 0, 'aduilt'], [89, 1, 1, 'Fortune, Miss Mabel Helen', 'female', 23.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, -6.69911764705882, 25, 240.0, 1, 'aduilt'], [90, 0, 3, 'Celotti, Mr. Francesco', 'male', 24.0, 0, 0, '343275', 8.05, nan, 'S', 6.923000000000001, -5.69911764705882, 22, -15.95, 0, 'aduilt'], [91, 0, 3, 'Christmann, Mr. Emil', 'male', 29.0, 0, 0, '343276', 8.05, nan, 'S', 6.923000000000001, -0.6991176470588201, 20, -20.95, 0, 'aduilt'], [92, 0, 3, 'Andreasson, Mr. Paul Edvin', 'male', 20.0, 0, 0, '347466', 7.8542, nan, 'S', 6.754612, -9.69911764705882, 26, -12.145800000000001, 0, 'aduilt'], [93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 1, 0, 'W.E.P. 5734', 61.175, 'E31', 'S', 52.610499999999995, 16.30088235294118, 27, 15.174999999999997, 0, 'aduilt'], [94, 0, 3, 'Dean, Mr. Bertram Frank', 'male', 26.0, 1, 2, 'C.A. 2315', 20.575, nan, 'S', 17.694499999999998, -3.69911764705882, 23, -5.425000000000001, 0, 'aduilt'], [95, 0, 3, 'Coxon, Mr. Daniel', 'male', 59.0, 0, 0, '364500', 7.25, nan, 'S', 6.235, 29.30088235294118, 17, -51.75, 0, 'aduilt'], [96, 0, 3, 'Shorney, Mr. Charles Joseph', 'male', nan, 0, 0, '374910', 8.05, nan, 'S', 6.923000000000001, nan, 27, nan, 0, 'aduilt'], [97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0, 'PC 17754', 34.6542, 'A5', 'C', 29.802612000000003, 41.30088235294118, 25, -36.3458, 0, 'senior'], [98, 1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 0, 1, 'PC 17759', 63.3583, 'D10 D12', 'C', 54.488138, -6.69911764705882, 31, 40.3583, 0, 'aduilt'], [99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 'female', 34.0, 0, 1, '231919', 23.0, nan, 'S', 19.78, 4.30088235294118, 36, -11.0, 1, 'aduilt'], [100, 0, 2, 'Kantor, Mr. Sinai', 'male', 34.0, 1, 0, '244367', 26.0, nan, 'S', 22.36, 4.30088235294118, 17, -8.0, 0, 'aduilt'], [101, 0, 3, 'Petranec, Miss Matilda', 'female', 28.0, 0, 0, '349245', 7.8958, nan, 'S', 6.790388, -1.69911764705882, 22, -20.1042, 1, 'aduilt'], [102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', 'male', nan, 0, 0, '349215', 7.8958, nan, 'S', 6.790388, nan, 32, nan, 0, 'aduilt'], [103, 0, 1, 'White, Mr. Richard Frasar', 'male', 21.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999, -8.69911764705882, 25, 56.287499999999994, 0, 'aduilt'], [104, 0, 3, 'Johansson, Mr. Gustaf Joel', 'male', 33.0, 0, 0, '7540', 8.6542, nan, 'S', 7.442612, 3.30088235294118, 26, -24.3458, 0, 'aduilt'], [105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 'male', 37.0, 2, 0, '3101276', 7.925, nan, 'S', 6.8155, 7.30088235294118, 30, -29.075, 0, 'aduilt'], [106, 0, 3, 'Mionoff, Mr. Stoytcho', 'male', 28.0, 0, 0, '349207', 7.8958, nan, 'S', 6.790388, -1.69911764705882, 21, -20.1042, 0, 'aduilt'], [107, 1, 3, 'Salkjelsvik, Miss Anna Kristine', 'female', 21.0, 0, 0, '343120', 7.65, nan, 'S', 6.579000000000001, -8.69911764705882, 31, -13.35, 1, 'aduilt'], [108, 1, 3, 'Moss, Mr. Albert Johan', 'male', nan, 0, 0, '312991', 7.775, nan, 'S', 6.6865000000000006, nan, 22, nan, 0, 'aduilt'], [109, 0, 3, 'Rekic, Mr. Tido', 'male', 38.0, 0, 0, '349249', 7.8958, nan, 'S', 6.790388, 8.30088235294118, 15, -30.1042, 0, 'aduilt'], [110, 1, 3, 'Moran, Miss Bertha', 'female', nan, 1, 0, '371110', 24.15, nan, 'Q', 20.769, nan, 18, nan, 1, 'aduilt'], [111, 0, 1, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 0, 0, '110465', 52.0, 'C110', 'S', 44.72, 17.30088235294118, 30, 5.0, 0, 'aduilt'], [112, 0, 3, 'Zabour, Miss Hileni', 'female', 14.5, 1, 0, '2665', 14.4542, nan, 'C', 12.430612, -15.19911764705882, 19, -0.04579999999999984, 1, 'child'], [113, 0, 3, 'Barton, Mr. David John', 'male', 22.0, 0, 0, '324669', 8.05, nan, 'S', 6.923000000000001, -7.69911764705882, 22, -13.95, 0, 'aduilt'], [114, 0, 3, 'Jussila, Miss Katriina', 'female', 20.0, 1, 0, '4136', 9.825, nan, 'S', 8.449499999999999, -9.69911764705882, 22, -10.175, 1, 'aduilt'], [115, 0, 3, 'Attalah, Miss Malake', 'female', 17.0, 0, 0, '2627', 14.4583, nan, 'C', 12.434137999999999, -12.69911764705882, 20, -2.5417000000000005, 1, 'child'], [116, 0, 3, 'Pekoniemi, Mr. Edvard', 'male', 21.0, 0, 0, 'STON/O 2. 3101294', 7.925, nan, 'S', 6.8155, -8.69911764705882, 21, -13.075, 0, 'aduilt'], [117, 0, 3, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0, '370369', 7.75, nan, 'Q', 6.665, 40.80088235294118, 20, -62.75, 0, 'senior'], [118, 0, 2, 'Turpin, Mr. William John Robert', 'male', 29.0, 1, 0, '11668', 21.0, nan, 'S', 18.06, -0.6991176470588201, 31, -8.0, 0, 'aduilt'], [119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', 212.867888, -5.69911764705882, 24, 223.5208, 0, 'aduilt'], [120, 0, 3, 'Andersson, Miss Ellis Anna Maria', 'female', 2.0, 4, 2, '347082', 31.275, nan, 'S', 26.8965, -27.69911764705882, 32, 29.275, 1, 'child'], [121, 0, 2, 'Hickman, Mr. Stanley George', 'male', 21.0, 2, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21, -8.69911764705882, 27, 52.5, 0, 'aduilt'], [122, 0, 3, 'Moore, Mr. Leonard Charles', 'male', nan, 0, 0, 'A4. 54510', 8.05, nan, 'S', 6.923000000000001, nan, 26, nan, 0, 'aduilt'], [123, 0, 2, 'Nasser, Mr. Nicholas', 'male', 32.5, 1, 0, '237736', 30.0708, nan, 'C', 25.860888, 2.80088235294118, 20, -2.4292000000000016, 0, 'aduilt'], [124, 1, 2, 'Webber, Miss Susan', 'female', 32.5, 0, 0, '27267', 13.0, 'E101', 'S', 11.18, 2.80088235294118, 18, -19.5, 1, 'aduilt'], [125, 0, 1, 'White, Mr. Percival Wayland', 'male', 54.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999, 24.30088235294118, 27, 23.287499999999994, 0, 'aduilt'], [126, 1, 3, 'Nicola-Yarred, Master Elias', 'male', 12.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862, -17.69911764705882, 27, -0.7583000000000002, 0, 'child'], [127, 0, 3, 'McMahon, Mr. Martin', 'male', nan, 0, 0, '370372', 7.75, nan, 'Q', 6.665, nan, 19, nan, 0, 'aduilt'], [128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 'male', 24.0, 0, 0, 'C 17369', 7.1417, nan, 'S', 6.141862, -5.69911764705882, 25, -16.8583, 0, 'aduilt'], [129, 1, 3, 'Peter, Miss Anna', 'female', nan, 1, 1, '2668', 22.3583, 'F E69', 'C', 19.228138, nan, 16, nan, 1, 'aduilt'], [130, 0, 3, 'Ekstrom, Mr. Johan', 'male', 45.0, 0, 0, '347061', 6.975, nan, 'S', 5.9985, 15.30088235294118, 18, -38.025, 0, 'aduilt'], [131, 0, 3, 'Drazenoic, Mr. Jozef', 'male', 33.0, 0, 0, '349241', 7.8958, nan, 'C', 6.790388, 3.30088235294118, 20, -25.1042, 0, 'aduilt'], [132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 'male', 20.0, 0, 0, 'SOTON/O.Q. 3101307', 7.05, nan, 'S', 6.063, -9.69911764705882, 30, -12.95, 0, 'aduilt'], [133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female', 47.0, 1, 0, 'A/5. 3337', 14.5, nan, 'S', 12.47, 17.30088235294118, 46, -32.5, 1, 'aduilt'], [134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female', 29.0, 1, 0, '228414', 26.0, nan, 'S', 22.36, -0.6991176470588201, 45, -3.0, 1, 'aduilt'], [135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 'male', 25.0, 0, 0, 'C.A. 29178', 13.0, nan, 'S', 11.18, -4.69911764705882, 30, -12.0, 0, 'aduilt'], [136, 0, 2, 'Richard, Mr. Emile', 'male', 23.0, 0, 0, 'SC/PARIS 2133', 15.0458, nan, 'C', 12.939388, -6.69911764705882, 18, -7.9542, 0, 'aduilt'], [137, 1, 1, 'Newsom, Miss Helen Monypeny', 'female', 19.0, 0, 2, '11752', 26.2833, 'D47', 'S', 22.603638, -10.69911764705882, 27, 7.2833000000000006, 1, 'aduilt'],

In [49]:
# Question 1
# printing first row
print(data[1])

[2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 61.303638, 8.30088235294118, 51, 33.2833, 1, 'aduilt']

In [51]:
#Question 2

for r in data:
  # age is the fifth item in the row (starting at 0)
  age = r[5]
  if age > 60:
    print(r)

[34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0, 'C.A. 24579', 10.5, nan, 'S', 9.03, 36.30088235294118, 21, -55.5, 0, 'senior']
[55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1, '113509', 61.9792, 'B30', 'C', 53.302112, 35.30088235294118, 30, -3.0208000000000013, 0, 'senior']
[97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0, 'PC 17754', 34.6542, 'A5', 'C', 29.802612000000003, 41.30088235294118, 25, -36.3458, 0, 'senior']
[117, 0, 3, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0, '370369', 7.75, nan, 'Q', 6.665, 40.80088235294118, 20, -62.75, 0, 'senior']
[171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male', 61.0, 0, 0, '111240', 33.5, 'B19', 'S', 28.81, 31.30088235294118, 25, -27.5, 0, 'senior']
[253, 0, 1, 'Stead, Mr. William Thomas', 'male', 62.0, 0, 0, '113514', 26.55, 'C87', 'S', 22.833000000000002, 32.30088235294118, 25, -35.45, 0, 'senior']
[276, 1, 1, 'Andrews, Miss Kornelia Theodosia', 'female', 63.0, 1, 0, '13502', 77.9583, 'D7', 'S', 67.04413799999999, 33.30088235294118, 32, 14.958299999999994, 1, 'senior']
[281, 0, 3, 'Duane, Mr. Frank', 'male', 65.0, 0, 0, '336439', 7.75, nan, 'Q', 6.665, 35.30088235294118, 16, -57.25, 0, 'senior']
[327, 0, 3, 'Nysveen, Mr. Johan Hansen', 'male', 61.0, 0, 0, '345364', 6.2375, nan, 'S', 5.36425, 31.30088235294118, 25, -54.7625, 0, 'senior']
[439, 0, 1, 'Fortune, Mr. Mark', 'male', 64.0, 1, 4, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, 34.30088235294118, 17, 199.0, 0, 'senior']
[457, 0, 1, 'Millet, Mr. Francis Davis', 'male', 65.0, 0, 0, '13509', 26.55, 'E38', 'S', 22.833000000000002, 35.30088235294118, 25, -38.45, 0, 'senior']
[484, 1, 3, 'Turkula, Mrs. (Hedwig)', 'female', 63.0, 0, 0, '4134', 9.5875, nan, 'S', 8.24525, 33.30088235294118, 22, -53.4125, 1, 'senior']
[494, 0, 1, 'Artagaveytia, Mr. Ramon', 'male', 71.0, 0, 0, 'PC 17609', 49.5042, nan, 'C', 42.573612, 41.30088235294118, 23, -21.495800000000003, 0, 'senior']
[546, 0, 1, 'Nicholson, Mr. Arthur Ernest', 'male', 64.0, 0, 0, '693', 26.0, nan, 'S', 22.36, 34.30088235294118, 28, -38.0, 0, 'senior']
[556, 0, 1, 'Wright, Mr. George', 'male', 62.0, 0, 0, '113807', 26.55, nan, 'S', 22.833000000000002, 32.30088235294118, 18, -35.45, 0, 'senior']
[571, 1, 2, 'Harris, Mr. George', 'male', 62.0, 0, 0, 'S.W./PP 752', 10.5, nan, 'S', 9.03, 32.30088235294118, 18, -51.5, 0, 'senior']
[626, 0, 1, 'Sutton, Mr. Frederick', 'male', 61.0, 0, 0, '36963', 32.3208, 'D50', 'S', 27.795887999999998, 31.30088235294118, 21, -28.6792, 0, 'senior']
[631, 1, 1, 'Barkworth, Mr. Algernon Henry Wilson', 'male', 80.0, 0, 0, '27042', 30.0, 'A23', 'S', 25.8, 50.30088235294118, 36, -50.0, 0, 'senior']
[673, 0, 2, 'Mitchell, Mr. Henry Michael', 'male', 70.0, 0, 0, 'C.A. 24580', 10.5, nan, 'S', 9.03, 40.30088235294118, 27, -59.5, 0, 'senior']
[746, 0, 1, 'Crosby, Capt. Edward Gifford', 'male', 70.0, 1, 1, 'WE/P 5735', 71.0, 'B22', 'S', 61.06, 40.30088235294118, 28, 1.0, 0, 'senior']
[830, 1, 1, 'Stone, Mrs. George Nelson (Martha Evelyn)', 'female', 62.0, 0, 0, '113572', 80.0, 'B28', nan, 68.8, 32.30088235294118, 41, 18.0, 1, 'senior']
[852, 0, 3, 'Svensson, Mr. Johan', 'male', 74.0, 0, 0, '347060', 7.775, nan, 'S', 6.6865000000000006, 44.30088235294118, 19, -66.225, 0, 'senior']

In [52]:
#Question 3

# column 4 is the gender index
for r in data: r.pop(4)
print(data)

[[1, 0, 3, 'Braund, Mr. Owen Harris', 22.0, 1, 0, 'A/5 21171', 7.25, nan, 'S', 6.235, -7.69911764705882, 23, -14.75, 0, 'aduilt'], [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C', 61.303638, 8.30088235294118, 51, 33.2833, 1, 'aduilt'], [3, 1, 3, 'Heikkinen, Miss Laina', 26.0, 0, 0, 'STON/O2. 3101282', 7.925, nan, 'S', 6.8155, -3.69911764705882, 21, -18.075, 1, 'aduilt'], [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 35.0, 1, 0, '113803', 53.1, 'C123', 'S', 45.666000000000004, 5.30088235294118, 44, 18.1, 1, 'aduilt'], [5, 0, 3, 'Allen, Mr. William Henry', 35.0, 0, 0, '373450', 8.05, nan, 'S', 6.923000000000001, 5.30088235294118, 24, -26.95, 0, 'aduilt'], [6, 0, 3, 'Moran, Mr. James', nan, 0, 0, '330877', 8.4583, nan, 'Q', 7.274138, nan, 16, nan, 0, 'aduilt'], [7, 0, 1, 'McCarthy, Mr. Timothy J', 54.0, 0, 0, '17463', 51.8625, 'E46', 'S', 44.601749999999996, 24.30088235294118, 23, -2.137500000000003, 0, 'aduilt'], [8, 0, 3, 'Palsson, Master Gosta Leonard', 2.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998, -27.69911764705882, 29, 19.075, 0, 'child'], [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 27.0, 0, 2, '347742', 11.1333, nan, 'S', 9.574638, -2.69911764705882, 49, -15.8667, 1, 'aduilt'], [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 14.0, 1, 0, '237736', 30.0708, nan, 'C', 25.860888, -15.69911764705882, 35, 16.0708, 1, 'child'], [11, 1, 3, 'Sandstrom, Miss Marguerite Rut', 4.0, 1, 1, 'PP 9549', 16.7, 'G6', 'S', 14.361999999999998, -25.69911764705882, 30, 12.7, 1, 'child'], [12, 1, 1, 'Bonnell, Miss Elizabeth', 58.0, 0, 0, '113783', 26.55, 'C103', 'S', 22.833000000000002, 28.30088235294118, 23, -31.45, 1, 'aduilt'], [13, 0, 3, 'Saundercock, Mr. William Henry', 20.0, 0, 0, 'A/5. 2151', 8.05, nan, 'S', 6.923000000000001, -9.69911764705882, 30, -11.95, 0, 'aduilt'], [14, 0, 3, 'Andersson, Mr. Anders Johan', 39.0, 1, 5, '347082', 31.275, nan, 'S', 26.8965, 9.30088235294118, 27, -7.725000000000001, 0, 'aduilt'], [15, 0, 3, 'Vestrom, Miss Hulda Amanda Adolfina', 14.0, 0, 0, '350406', 7.8542, nan, 'S', 6.754612, -15.69911764705882, 35, -6.1458, 1, 'child'], [16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 55.0, 0, 0, '248706', 16.0, nan, 'S', 13.76, 25.30088235294118, 32, -39.0, 1, 'aduilt'], [17, 0, 3, 'Rice, Master Eugene', 2.0, 4, 1, '382652', 29.125, nan, 'Q', 25.0475, -27.69911764705882, 19, 27.125, 0, 'child'], [18, 1, 2, 'Williams, Mr. Charles Eugene', nan, 0, 0, '244373', 13.0, nan, 'S', 11.18, nan, 28, nan, 0, 'aduilt'], [19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 31.0, 1, 0, '345763', 18.0, nan, 'S', 15.48, 1.30088235294118, 55, -13.0, 1, 'aduilt'], [20, 1, 3, 'Masselmani, Mrs. Fatima', nan, 0, 0, '2649', 7.225, nan, 'C', 6.2135, nan, 23, nan, 1, 'aduilt'], [21, 0, 2, 'Fynney, Mr. Joseph J', 35.0, 0, 0, '239865', 26.0, nan, 'S', 22.36, 5.30088235294118, 20, -9.0, 0, 'aduilt'], [22, 1, 2, 'Beesley, Mr. Lawrence', 34.0, 0, 0, '248698', 13.0, 'D56', 'S', 11.18, 4.30088235294118, 21, -21.0, 0, 'aduilt'], [23, 1, 3, 'McGowan, Miss Anna "Annie"', 15.0, 0, 0, '330923', 8.0292, nan, 'Q', 6.905111999999999, -14.69911764705882, 26, -6.9708000000000006, 1, 'child'], [24, 1, 1, 'Sloper, Mr. William Thompson', 28.0, 0, 0, '113788', 35.5, 'A6', 'S', 30.53, -1.69911764705882, 28, 7.5, 0, 'aduilt'], [25, 0, 3, 'Palsson, Miss Torborg Danira', 8.0, 3, 1, '349909', 21.075, nan, 'S', 18.124499999999998, -21.69911764705882, 28, 13.075, 1, 'child'], [26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 38.0, 1, 5, '347077', 31.3875, nan, 'S', 26.99325, 8.30088235294118, 57, -6.612500000000001, 1, 'aduilt'], [27, 0, 3, 'Emir, Mr. Farred Chehab', nan, 0, 0, '2631', 7.225, nan, 'C', 6.2135, nan, 23, nan, 0, 'aduilt'], [28, 0, 1, 'Fortune, Mr. Charles Alexander', 19.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, -10.69911764705882, 30, 244.0, 0, 'aduilt'], [29, 1, 3, 'O\'Dwyer, Miss Ellen "Nellie"', nan, 0, 0, '330959', 7.8792, nan, 'Q', 6.7761119999999995, nan, 28, nan, 1, 'aduilt'], [30, 0, 3, 'Todoroff, Mr. Lalio', nan, 0, 0, '349216', 7.8958, nan, 'S', 6.790388, nan, 19, nan, 0, 'aduilt'], [31, 0, 1, 'Uruchurtu, Don. Manuel E', 40.0, 0, 0, 'PC 17601', 27.7208, nan, 'C', 23.839888, 10.30088235294118, 24, -12.2792, 0, 'aduilt'], [32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', nan, 1, 0, 'PC 17569', 146.5208, 'B78', 'C', 126.00788800000001, nan, 46, nan, 1, 'aduilt'], [33, 1, 3, 'Glynn, Miss Mary Agatha', nan, 0, 0, '335677', 7.75, nan, 'Q', 6.665, nan, 23, nan, 1, 'aduilt'], [34, 0, 2, 'Wheadon, Mr. Edward H', 66.0, 0, 0, 'C.A. 24579', 10.5, nan, 'S', 9.03, 36.30088235294118, 21, -55.5, 0, 'senior'], [35, 0, 1, 'Meyer, Mr. Edgar Joseph', 28.0, 1, 0, 'PC 17604', 82.1708, nan, 'C', 70.666888, -1.69911764705882, 23, 54.1708, 0, 'aduilt'], [36, 0, 1, 'Holverson, Mr. Alexander Oskar', 42.0, 1, 0, '113789', 52.0, nan, 'S', 44.72, 12.30088235294118, 30, 10.0, 0, 'aduilt'], [37, 1, 3, 'Mamee, Mr. Hanna', nan, 0, 0, '2677', 7.2292, nan, 'C', 6.217111999999999, nan, 16, nan, 0, 'aduilt'], [38, 0, 3, 'Cann, Mr. Ernest Charles', 21.0, 0, 0, 'A./5. 2152', 8.05, nan, 'S', 6.923000000000001, -8.69911764705882, 24, -12.95, 0, 'aduilt'], [39, 0, 3, 'Vander Planke, Miss Augusta Maria', 18.0, 2, 0, '345764', 18.0, nan, 'S', 15.48, -11.69911764705882, 33, 0.0, 1, 'aduilt'], [40, 1, 3, 'Nicola-Yarred, Miss Jamila', 14.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862, -15.69911764705882, 26, -2.7583, 1, 'child'], [41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 40.0, 1, 0, '7546', 9.475, nan, 'S', 8.1485, 10.30088235294118, 46, -30.525, 1, 'aduilt'], [42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 27.0, 1, 0, '11668', 21.0, nan, 'S', 18.06, -2.69911764705882, 56, -6.0, 1, 'aduilt'], [43, 0, 3, 'Kraeff, Mr. Theodor', nan, 0, 0, '349253', 7.8958, nan, 'C', 6.790388, nan, 19, nan, 0, 'aduilt'], [44, 1, 2, 'Laroche, Miss Simonne Marie Anne Andree', 3.0, 1, 2, 'SC/Paris 2123', 41.5792, nan, 'C', 35.758112, -26.69911764705882, 39, 38.5792, 1, 'child'], [45, 1, 3, 'Devaney, Miss Margaret Delia', 19.0, 0, 0, '330958', 7.8792, nan, 'Q', 6.7761119999999995, -10.69911764705882, 28, -11.1208, 1, 'aduilt'], [46, 0, 3, 'Rogers, Mr. William John', nan, 0, 0, 'S.C./A.4. 23567', 8.05, nan, 'S', 6.923000000000001, nan, 24, nan, 0, 'aduilt'], [47, 0, 3, 'Lennon, Mr. Denis', nan, 1, 0, '370371', 15.5, nan, 'Q', 13.33, nan, 17, nan, 0, 'aduilt'], [48, 1, 3, "O'Driscoll, Miss Bridget", nan, 0, 0, '14311', 7.75, nan, 'Q', 6.665, nan, 24, nan, 1, 'aduilt'], [49, 0, 3, 'Samaan, Mr. Youssef', nan, 2, 0, '2662', 21.6792, nan, 'C', 18.644112, nan, 19, nan, 0, 'aduilt'], [50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 18.0, 1, 0, '349237', 17.8, nan, 'S', 15.308, -11.69911764705882, 45, -0.1999999999999993, 1, 'aduilt'], [51, 0, 3, 'Panula, Master Juha Niilo', 7.0, 4, 1, '3101295', 39.6875, nan, 'S', 34.13125, -22.69911764705882, 25, 32.6875, 0, 'child'], [52, 0, 3, 'Nosworthy, Mr. Richard Cater', 21.0, 0, 0, 'A/4. 39886', 7.8, nan, 'S', 6.708, -8.69911764705882, 28, -13.2, 0, 'aduilt'], [53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 49.0, 1, 0, 'PC 17572', 76.7292, 'D33', 'C', 65.98711200000001, 19.30088235294118, 40, 27.729200000000006, 1, 'aduilt'], [54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 29.0, 1, 0, '2926', 26.0, nan, 'S', 22.36, -0.6991176470588201, 50, -3.0, 1, 'aduilt'], [55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 65.0, 0, 1, '113509', 61.9792, 'B30', 'C', 53.302112, 35.30088235294118, 30, -3.0208000000000013, 0, 'senior'], [56, 1, 1, 'Woolner, Mr. Hugh', nan, 0, 0, '19947', 35.5, 'C52', 'S', 30.53, nan, 17, nan, 0, 'aduilt'], [57, 1, 2, 'Rugg, Miss Emily', 21.0, 0, 0, 'C.A. 31026', 10.5, nan, 'S', 9.03, -8.69911764705882, 16, -10.5, 1, 'aduilt'], [58, 0, 3, 'Novel, Mr. Mansouer', 28.5, 0, 0, '2697', 7.2292, nan, 'C', 6.217111999999999, -1.19911764705882, 19, -21.2708, 0, 'aduilt'], [59, 1, 2, 'West, Miss Constance Mirium', 5.0, 1, 2, 'C.A. 34651', 27.75, nan, 'S', 23.865, -24.69911764705882, 27, 22.75, 1, 'child'], [60, 0, 3, 'Goodwin, Master William Frederick', 11.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996, -18.69911764705882, 33, 35.9, 0, 'child'], [61, 0, 3, 'Sirayanian, Mr. Orsen', 22.0, 0, 0, '2669', 7.2292, nan, 'C', 6.217111999999999, -7.69911764705882, 21, -14.770800000000001, 0, 'aduilt'], [62, 1, 1, 'Icard, Miss Amelie', 38.0, 0, 0, '113572', 80.0, 'B28', nan, 68.8, 8.30088235294118, 18, 42.0, 1, 'aduilt'], [63, 0, 1, 'Harris, Mr. Henry Birkhardt', 45.0, 1, 0, '36973', 83.475, 'C83', 'S', 71.7885, 15.30088235294118, 27, 38.474999999999994, 0, 'aduilt'], [64, 0, 3, 'Skoog, Master Harald', 4.0, 3, 2, '347088', 27.9, nan, 'S', 23.994, -25.69911764705882, 20, 23.9, 0, 'child'], [65, 0, 1, 'Stewart, Mr. Albert A', nan, 0, 0, 'PC 17605', 27.7208, nan, 'C', 23.839888, nan, 21, nan, 0, 'aduilt'], [66, 1, 3, 'Moubarek, Master Gerios', nan, 1, 1, '2661', 15.2458, nan, 'C', 13.111388, nan, 23, nan, 0, 'aduilt'], [67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 29.0, 0, 0, 'C.A. 29395', 10.5, 'F33', 'S', 9.03, -0.6991176470588201, 28, -18.5, 1, 'aduilt'], [68, 0, 3, 'Crease, Mr. Ernest James', 19.0, 0, 0, 'S.P. 3464', 8.1583, nan, 'S', 7.016138000000001, -10.69911764705882, 24, -10.8417, 0, 'aduilt'], [69, 1, 3, 'Andersson, Miss Erna Alexandra', 17.0, 4, 2, '3101281', 7.925, nan, 'S', 6.8155, -12.69911764705882, 30, -9.075, 1, 'child'], [70, 0, 3, 'Kink, Mr. Vincenz', 26.0, 2, 0, '315151', 8.6625, nan, 'S', 7.44975, -3.69911764705882, 17, -17.3375, 0, 'aduilt'], [71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 32.0, 0, 0, 'C.A. 33111', 10.5, nan, 'S', 9.03, 2.30088235294118, 26, -21.5, 0, 'aduilt'], [72, 0, 3, 'Goodwin, Miss Lillian Amy', 16.0, 5, 2, 'CA 2144', 46.9, nan, 'S', 40.333999999999996, -13.69911764705882, 25, 30.9, 1, 'child'], [73, 0, 2, 'Hood, Mr. Ambrose Jr', 21.0, 0, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21, -8.69911764705882, 20, 52.5, 0, 'aduilt'], [74, 0, 3, 'Chronopoulos, Mr. Apostolos', 26.0, 1, 0, '2680', 14.4542, nan, 'C', 12.430612, -3.69911764705882, 27, -11.5458, 0, 'aduilt'], [75, 1, 3, 'Bing, Mr. Lee', 32.0, 0, 0, '1601', 56.4958, nan, 'S', 48.586388, 2.30088235294118, 13, 24.495800000000003, 0, 'aduilt'], [76, 0, 3, 'Moen, Mr. Sigurd Hansen', 25.0, 0, 0, '348123', 7.65, 'F G73', 'S', 6.579000000000001, -4.69911764705882, 23, -17.35, 0, 'aduilt'], [77, 0, 3, 'Staneff, Mr. Ivan', nan, 0, 0, '349208', 7.8958, nan, 'S', 6.790388, nan, 17, nan, 0, 'aduilt'], [78, 0, 3, 'Moutal, Mr. Rahamin Haim', nan, 0, 0, '374746', 8.05, nan, 'S', 6.923000000000001, nan, 24, nan, 0, 'aduilt'], [79, 1, 2, 'Caldwell, Master Alden Gates', 0.83, 0, 2, '248738', 29.0, nan, 'S', 24.94, -28.86911764705882, 28, 28.17, 0, 'child'], [80, 1, 3, 'Dowdell, Miss Elizabeth', 30.0, 0, 0, '364516', 12.475, nan, 'S', 10.7285, 0.30088235294117993, 23, -17.525, 1, 'aduilt'], [81, 0, 3, 'Waelens, Mr. Achille', 22.0, 0, 0, '345767', 9.0, nan, 'S', 7.74, -7.69911764705882, 20, -13.0, 0, 'aduilt'], [82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 29.0, 0, 0, '345779', 9.5, nan, 'S', 8.17, -0.6991176470588201, 27, -19.5, 0, 'aduilt'], [83, 1, 3, 'McDermott, Miss Brigdet Delia', nan, 0, 0, '330932', 7.7875, nan, 'Q', 6.6972499999999995, nan, 29, nan, 1, 'aduilt'], [84, 0, 1, 'Carrau, Mr. Francisco M', 28.0, 0, 0, '113059', 47.1, nan, 'S', 40.506, -1.69911764705882, 23, 19.1, 0, 'aduilt'], [85, 1, 2, 'Ilett, Miss Bertha', 17.0, 0, 0, 'SO/C 14885', 10.5, nan, 'S', 9.03, -12.69911764705882, 18, -6.5, 1, 'child'], [86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 33.0, 3, 0, '3101278', 15.85, nan, 'S', 13.631, 3.30088235294118, 55, -17.15, 1, 'aduilt'], [87, 0, 3, 'Ford, Mr. William Neal', 16.0, 1, 3, 'W./C. 6608', 34.375, nan, 'S', 29.5625, -13.69911764705882, 22, 18.375, 0, 'child'], [88, 0, 3, 'Slocovski, Mr. Selman Francis', nan, 0, 0, 'SOTON/OQ 392086', 8.05, nan, 'S', 6.923000000000001, nan, 29, nan, 0, 'aduilt'], [89, 1, 1, 'Fortune, Miss Mabel Helen', 23.0, 3, 2, '19950', 263.0, 'C23 C25 C27', 'S', 226.18, -6.69911764705882, 25, 240.0, 1, 'aduilt'], [90, 0, 3, 'Celotti, Mr. Francesco', 24.0, 0, 0, '343275', 8.05, nan, 'S', 6.923000000000001, -5.69911764705882, 22, -15.95, 0, 'aduilt'], [91, 0, 3, 'Christmann, Mr. Emil', 29.0, 0, 0, '343276', 8.05, nan, 'S', 6.923000000000001, -0.6991176470588201, 20, -20.95, 0, 'aduilt'], [92, 0, 3, 'Andreasson, Mr. Paul Edvin', 20.0, 0, 0, '347466', 7.8542, nan, 'S', 6.754612, -9.69911764705882, 26, -12.145800000000001, 0, 'aduilt'], [93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 46.0, 1, 0, 'W.E.P. 5734', 61.175, 'E31', 'S', 52.610499999999995, 16.30088235294118, 27, 15.174999999999997, 0, 'aduilt'], [94, 0, 3, 'Dean, Mr. Bertram Frank', 26.0, 1, 2, 'C.A. 2315', 20.575, nan, 'S', 17.694499999999998, -3.69911764705882, 23, -5.425000000000001, 0, 'aduilt'], [95, 0, 3, 'Coxon, Mr. Daniel', 59.0, 0, 0, '364500', 7.25, nan, 'S', 6.235, 29.30088235294118, 17, -51.75, 0, 'aduilt'], [96, 0, 3, 'Shorney, Mr. Charles Joseph', nan, 0, 0, '374910', 8.05, nan, 'S', 6.923000000000001, nan, 27, nan, 0, 'aduilt'], [97, 0, 1, 'Goldschmidt, Mr. George B', 71.0, 0, 0, 'PC 17754', 34.6542, 'A5', 'C', 29.802612000000003, 41.30088235294118, 25, -36.3458, 0, 'senior'], [98, 1, 1, 'Greenfield, Mr. William Bertram', 23.0, 0, 1, 'PC 17759', 63.3583, 'D10 D12', 'C', 54.488138, -6.69911764705882, 31, 40.3583, 0, 'aduilt'], [99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 34.0, 0, 1, '231919', 23.0, nan, 'S', 19.78, 4.30088235294118, 36, -11.0, 1, 'aduilt'], [100, 0, 2, 'Kantor, Mr. Sinai', 34.0, 1, 0, '244367', 26.0, nan, 'S', 22.36, 4.30088235294118, 17, -8.0, 0, 'aduilt'], [101, 0, 3, 'Petranec, Miss Matilda', 28.0, 0, 0, '349245', 7.8958, nan, 'S', 6.790388, -1.69911764705882, 22, -20.1042, 1, 'aduilt'], [102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', nan, 0, 0, '349215', 7.8958, nan, 'S', 6.790388, nan, 32, nan, 0, 'aduilt'], [103, 0, 1, 'White, Mr. Richard Frasar', 21.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999, -8.69911764705882, 25, 56.287499999999994, 0, 'aduilt'], [104, 0, 3, 'Johansson, Mr. Gustaf Joel', 33.0, 0, 0, '7540', 8.6542, nan, 'S', 7.442612, 3.30088235294118, 26, -24.3458, 0, 'aduilt'], [105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 37.0, 2, 0, '3101276', 7.925, nan, 'S', 6.8155, 7.30088235294118, 30, -29.075, 0, 'aduilt'], [106, 0, 3, 'Mionoff, Mr. Stoytcho', 28.0, 0, 0, '349207', 7.8958, nan, 'S', 6.790388, -1.69911764705882, 21, -20.1042, 0, 'aduilt'], [107, 1, 3, 'Salkjelsvik, Miss Anna Kristine', 21.0, 0, 0, '343120', 7.65, nan, 'S', 6.579000000000001, -8.69911764705882, 31, -13.35, 1, 'aduilt'], [108, 1, 3, 'Moss, Mr. Albert Johan', nan, 0, 0, '312991', 7.775, nan, 'S', 6.6865000000000006, nan, 22, nan, 0, 'aduilt'], [109, 0, 3, 'Rekic, Mr. Tido', 38.0, 0, 0, '349249', 7.8958, nan, 'S', 6.790388, 8.30088235294118, 15, -30.1042, 0, 'aduilt'], [110, 1, 3, 'Moran, Miss Bertha', nan, 1, 0, '371110', 24.15, nan, 'Q', 20.769, nan, 18, nan, 1, 'aduilt'], [111, 0, 1, 'Porter, Mr. Walter Chamberlain', 47.0, 0, 0, '110465', 52.0, 'C110', 'S', 44.72, 17.30088235294118, 30, 5.0, 0, 'aduilt'], [112, 0, 3, 'Zabour, Miss Hileni', 14.5, 1, 0, '2665', 14.4542, nan, 'C', 12.430612, -15.19911764705882, 19, -0.04579999999999984, 1, 'child'], [113, 0, 3, 'Barton, Mr. David John', 22.0, 0, 0, '324669', 8.05, nan, 'S', 6.923000000000001, -7.69911764705882, 22, -13.95, 0, 'aduilt'], [114, 0, 3, 'Jussila, Miss Katriina', 20.0, 1, 0, '4136', 9.825, nan, 'S', 8.449499999999999, -9.69911764705882, 22, -10.175, 1, 'aduilt'], [115, 0, 3, 'Attalah, Miss Malake', 17.0, 0, 0, '2627', 14.4583, nan, 'C', 12.434137999999999, -12.69911764705882, 20, -2.5417000000000005, 1, 'child'], [116, 0, 3, 'Pekoniemi, Mr. Edvard', 21.0, 0, 0, 'STON/O 2. 3101294', 7.925, nan, 'S', 6.8155, -8.69911764705882, 21, -13.075, 0, 'aduilt'], [117, 0, 3, 'Connors, Mr. Patrick', 70.5, 0, 0, '370369', 7.75, nan, 'Q', 6.665, 40.80088235294118, 20, -62.75, 0, 'senior'], [118, 0, 2, 'Turpin, Mr. William John Robert', 29.0, 1, 0, '11668', 21.0, nan, 'S', 18.06, -0.6991176470588201, 31, -8.0, 0, 'aduilt'], [119, 0, 1, 'Baxter, Mr. Quigg Edmond', 24.0, 0, 1, 'PC 17558', 247.5208, 'B58 B60', 'C', 212.867888, -5.69911764705882, 24, 223.5208, 0, 'aduilt'], [120, 0, 3, 'Andersson, Miss Ellis Anna Maria', 2.0, 4, 2, '347082', 31.275, nan, 'S', 26.8965, -27.69911764705882, 32, 29.275, 1, 'child'], [121, 0, 2, 'Hickman, Mr. Stanley George', 21.0, 2, 0, 'S.O.C. 14879', 73.5, nan, 'S', 63.21, -8.69911764705882, 27, 52.5, 0, 'aduilt'], [122, 0, 3, 'Moore, Mr. Leonard Charles', nan, 0, 0, 'A4. 54510', 8.05, nan, 'S', 6.923000000000001, nan, 26, nan, 0, 'aduilt'], [123, 0, 2, 'Nasser, Mr. Nicholas', 32.5, 1, 0, '237736', 30.0708, nan, 'C', 25.860888, 2.80088235294118, 20, -2.4292000000000016, 0, 'aduilt'], [124, 1, 2, 'Webber, Miss Susan', 32.5, 0, 0, '27267', 13.0, 'E101', 'S', 11.18, 2.80088235294118, 18, -19.5, 1, 'aduilt'], [125, 0, 1, 'White, Mr. Percival Wayland', 54.0, 0, 1, '35281', 77.2875, 'D26', 'S', 66.46724999999999, 24.30088235294118, 27, 23.287499999999994, 0, 'aduilt'], [126, 1, 3, 'Nicola-Yarred, Master Elias', 12.0, 1, 0, '2651', 11.2417, nan, 'C', 9.667862, -17.69911764705882, 27, -0.7583000000000002, 0, 'child'], [127, 0, 3, 'McMahon, Mr. Martin', nan, 0, 0, '370372', 7.75, nan, 'Q', 6.665, nan, 19, nan, 0, 'aduilt'], [128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 24.0, 0, 0, 'C 17369', 7.1417, nan, 'S', 6.141862, -5.69911764705882, 25, -16.8583, 0, 'aduilt'], [129, 1, 3, 'Peter, Miss Anna', nan, 1, 1, '2668', 22.3583, 'F E69', 'C', 19.228138, nan, 16, nan, 1, 'aduilt'], [130, 0, 3, 'Ekstrom, Mr. Johan', 45.0, 0, 0, '347061', 6.975, nan, 'S', 5.9985, 15.30088235294118, 18, -38.025, 0, 'aduilt'], [131, 0, 3, 'Drazenoic, Mr. Jozef', 33.0, 0, 0, '349241', 7.8958, nan, 'C', 6.790388, 3.30088235294118, 20, -25.1042, 0, 'aduilt'], [132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 20.0, 0, 0, 'SOTON/O.Q. 3101307', 7.05, nan, 'S', 6.063, -9.69911764705882, 30, -12.95, 0, 'aduilt'], [133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 47.0, 1, 0, 'A/5. 3337', 14.5, nan, 'S', 12.47, 17.30088235294118, 46, -32.5, 1, 'aduilt'], [134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 29.0, 1, 0, '228414', 26.0, nan, 'S', 22.36, -0.6991176470588201, 45, -3.0, 1, 'aduilt'], [135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 25.0, 0, 0, 'C.A. 29178', 13.0, nan, 'S', 11.18, -4.69911764705882, 30, -12.0, 0, 'aduilt'], [136, 0, 2, 'Richard, Mr. Emile', 23.0, 0, 0, 'SC/PARIS 2133', 15.0458, nan, 'C', 12.939388, -6.69911764705882, 18, -7.9542, 0, 'aduilt'], [137, 1, 1, 'Newsom, Miss Helen Monypeny', 19.0, 0, 2, '11752', 26.2833, 'D47', 'S', 22.603638, -10.69911764705882, 27, 7.2833000000000006, 1, 'aduilt'], [138, 0, 1, 'Futrelle, Mr. Jacques Heath', 37.0, 1, 0, '113803', 53.1, 'C123', 'S', 45.666000000000004, 7.30088235294118, 27, 16.1, 0, 'aduilt'], [139, 0, 3, 'Osen, Mr. Olaf Elon', 16.0, 0, 0, '7534', 9.2167, nan, 'S', 7.926361999999999, -13.69911764705882, 19, -6.7833000000000006, 0, 'child'], [140, 0, 1, 'Giglio, Mr. Victor', 24.0, 0, 0, 'PC 17593', 79.2, 'B86', 'C', 68.112, -5.69911764705882, 18, 55.2, 0, 'aduilt'], [141, 0, 3, 'Boulos, Mrs. Joseph (Sultana)', nan, 0, 2, '2678', 15.2458, nan, 'C', 13.111388, nan, 29, nan, 1, 'aduilt'], [142, 1, 3, 'Nysten, Miss Anna Sofia', 22.0, 0, 0, '347081', 7.75, nan, 'S', 6.665, -7.69911764705882, 23, -14.25, 1, 'aduilt'], [143, 1, 3, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 24.0, 1, 0, 'STON/O2. 3101279', 15.85, nan, 'S', 13.631, -5.69911764705882, 52, -8.15, 1, 'aduilt'], [144, 0, 3, 'Burke, Mr. Jeremiah', 19.0, 0, 0, '365222', 6.75, nan, 'Q', 5.805, -10.69911764705882, 19, -12.25, 0, 'aduilt'], [145, 0, 2, 'Andrew, Mr. Edgardo Samuel', 18.0, 0, 0, '231945', 11.5, nan, 'S', 9.89, -11.69911764705882, 26, -6.5, 0, 'aduilt'], [146, 0, 2, 'Nicholls, Mr. Joseph Charles', 19.0, 1, 1, 'C.A. 33112', 36.75, nan, 'S', 31.605, -10

#Comparing Execution Time

1. Using pandas and numpy, it excecuted in 0.005s. With simply python code it excecuted in 0.018s.

2. Using pandas/numpy, excecuted in 0.046s. With just python, excecuted in 0.013s

3. Using pandas/numpy, excecuted in 0.085s. With just python, excecuted in 0.068s

For the first question it seems that using the libraries was much more efficient. For the second and third it appears that the standard python code excecuted quicker.